python -m unittest test_bigraph.py
python -m unittest test_conv.py
python -m unittest test_dataloader.py
python -m unittest test_graph.py
python -m unittest test_graph_op.py
python -m unittest test_hetergraph.py
python -m unittest test_math.py
python -m unittest test_partition.py
python -m unittest test_sample.py
python -m unittest test_static_graph.py
