model_name: Node2vec
learning_rate: 0.0025

sample_workers: 10
batch_size: 512
neg_num: 20
walk_len: 40
win_size: 10
neg_sample_type: average
embed_size: 128
p: 0.25
q: 0.25

multiclass_learning_rate: 0.025
