# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: feed_click.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='feed_click.proto',
  package='rec.uudm',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x10\x66\x65\x65\x64_click.proto\x12\x08rec.uudm\"g\n\tFeedClick\x12\x0b\n\x03rid\x18\x01 \x02(\x04\x12\n\n\x02ts\x18\x02 \x02(\x04\x12\x10\n\x08\x64uration\x18\x03 \x01(\x02\x12\x11\n\tpage_type\x18\x04 \x01(\x05\x12\n\n\x02st\x18\x05 \x01(\x05\x12\x10\n\x08rid_type\x18\x06 \x01(\x05\"2\n\rUserFeedClick\x12!\n\x04\x62\x65ha\x18\x01 \x03(\x0b\x32\x13.rec.uudm.FeedClick')
)


_FEEDCLICK = _descriptor.Descriptor(
  name='FeedClick',
  full_name='rec.uudm.FeedClick',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rid', full_name='rec.uudm.FeedClick.rid', index=0,
      number=1, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ts', full_name='rec.uudm.FeedClick.ts', index=1,
      number=2, type=4, cpp_type=4, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='duration', full_name='rec.uudm.FeedClick.duration', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='page_type', full_name='rec.uudm.FeedClick.page_type', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='st', full_name='rec.uudm.FeedClick.st', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rid_type', full_name='rec.uudm.FeedClick.rid_type', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=133,
)


_USERFEEDCLICK = _descriptor.Descriptor(
  name='UserFeedClick',
  full_name='rec.uudm.UserFeedClick',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='beha', full_name='rec.uudm.UserFeedClick.beha', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=185,
)

_USERFEEDCLICK.fields_by_name['beha'].message_type = _FEEDCLICK
DESCRIPTOR.message_types_by_name['FeedClick'] = _FEEDCLICK
DESCRIPTOR.message_types_by_name['UserFeedClick'] = _USERFEEDCLICK
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FeedClick = _reflection.GeneratedProtocolMessageType('FeedClick', (_message.Message,), {
  'DESCRIPTOR' : _FEEDCLICK,
  '__module__' : 'feed_click_pb2'
  # @@protoc_insertion_point(class_scope:rec.uudm.FeedClick)
  })
_sym_db.RegisterMessage(FeedClick)

UserFeedClick = _reflection.GeneratedProtocolMessageType('UserFeedClick', (_message.Message,), {
  'DESCRIPTOR' : _USERFEEDCLICK,
  '__module__' : 'feed_click_pb2'
  # @@protoc_insertion_point(class_scope:rec.uudm.UserFeedClick)
  })
_sym_db.RegisterMessage(UserFeedClick)


# @@protoc_insertion_point(module_scope)
