# This is a basic workflow to help you get started with Actions

name: Publish to PyPI

# Controls when the workflow will run
on:
  # Triggers the workflow on push tags
  push:
    tags:
      - '*'

jobs:
  build_wheels:
    name: Build ${{ matrix.os }} wheels for ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'macos-latest' ]
        arch: [ 'x86_64' ]
        cibw_python: [ "cp*" ]
    steps:
      - uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          
      - uses: docker/setup-qemu-action@v1
        if: runner.os == 'Linux'
        name: Set up QEMU
      
      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel
      
      - name: Build wheels for CPython
        run: |
          python -m cibuildwheel --output-dir dist
        env:
          CIBW_BUILD: ${{ matrix.cibw_python }}
          CIBW_ARCHS: ${{ matrix.arch }}
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
          CIBW_BEFORE_BUILD: "pip install -r requirements.txt cython>=0.29.21"
          CIBW_SKIP: "*-musllinux_*"
          CIBW_BEFORE_ALL_LINUX: >
            yum -y update &&
            yum install -y zlib-devel bzip2-devel lzo-devel
            
      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
